### ISSUE TITLE
Toolbar and statusbar widgets are not in dark mode when my system is in dark mode

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-qt-browser#100]
So this is what it looks like on macOS, makes my eyes bleed:

<img width="1138" alt="Screen Shot 2022-04-05 at 22 18 08" src="https://user-images.githubusercontent.com/2046265/161842014-de0b0dbe-b047-4231-bf43-b42aab20299a.png">

**Comment by larsoner** [comment]
I fixed this in https://github.com/mne-tools/mne-qt-browser/pull/66, I suspect some PR to MNE-Python after https://github.com/mne-tools/mne-python/pull/10414 (which was needed as well) broke this actually :(

cc @GuillaumeFavelier this is probably related to some of the recent theme refactoring(s). We have to be careful about when we set stylesheets and such.

@hoechenberger can you 1) check that switching to MNE-Python `[6e2c52c](https://github.com/mne-tools/mne-python/commit/6e2c52c592be02de3c798c98b21cfdc1d6e264ad)` works, and then if so 2) `git bisect` to figure out which PR broke things? I'm guessing it might be https://github.com/mne-tools/mne-python/commit/4301092691d279314d3a46ee58de66a6f3a6152a / https://github.com/mne-tools/mne-python/pull/10456 because IIRC it messed with themes most recently, but it's very possible I'm wrong!

**Comment by hoechenberger** [comment]
In fact I didn't even check my version of MNE-Python, I will check to be running the latest version tomorrow to see if the problem persists. Maybe there's nothing wrong after all …
