### ISSUE TITLE
Visualization of single channel annotations

### ISSUE THREAD

**Issue by marsipu** [mne-tools/mne-qt-browser#123]
**Is your feature request related to a problem? Please describe.**
Support for visualization of channel-specific annotations as described in mne-tools/mne-python#8946 and mne-tools/mne-python#8947 and #71 .

**Describe the solution you'd like**
Currently annotations are displayed by use of pyqtgraph's [LinearRegionItem](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/linearregionitem.html).
By setting `span` it should be possible to draw annotations only for single channels.
If we want subsegmented Regions, it might be better for performance if we modified the `paint`-method of `AnnotationRegion`(which is the currently used subclass of `LinearRegionItem`) to draw rectangles only where channels are active. So there would be still just on `AnnotationRegion` per marked timespan.

Also the following could be added:
- [ ] Shift+Clicking on channels inside annotations add/remove them from the annotation
- [ ] A dialog as suggested in #71 to select channels

**Describe alternatives you've considered**
Pyqtgraph's [ROI](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/roi.html) could also be an alternative, but I think it has much more functionality we don't need.

**Comment by prlabu** [comment]
Anything new on this? I am looking to visualize annotations for subsets of channels, exactly as you describe!

**Comment by larsoner** [comment]
No I don't think anyone has worked on it yet

**Comment by nmarkowitz** [comment]
Hi, I'm going to give this a try. Is there someone in the MNE dev team that could potentially give me pointers on how to best do this? I have thoughts but I think I would need to make new properties to store channel information for annotations.

**Comment by larsoner** [comment]
@nmarkowitz Annotations already has a `ch_names` attribute, see https://mne.tools/dev/generated/mne.Annotations.html . So really at this point it's mostly an issue of how to actually display and interact with the channel-specific annotations rather than how to store the annotations themselves in an object.

**Comment by drammock** [comment]
My thoughts: split this into 2 PRs:

1. ONLY adds visualization of existing per-channel annotations. Creating new per-channel annotations must still be done through code.
2. adds the ability to create per-channel annotations through the GUI

for the second one, I think the interaction design needs some brainstorming. Possible ideas:

- maybe we need a toggle to switch from "all-channels" mode to "specific-channels" mode
- maybe adding specific-channel annotations is always a 3-step process: create an all-channels annotation, convert it to a specific-channels annotation, then specify which channels it applies to (somehow)

**Comment by nmarkowitz** [comment]
I'll start with some basic. While in annotation mode, shift+click a channel name on the channel name or the channel trace will make that channel part of the annotation. I'll attend office hours tomorrow as well if we want to further discuss

**Comment by larsoner** [comment]
I expected the channel-specific annotation to *only* cover the annotated channel(s) rather than spanning all channels in one color and the annotated channel in a different (darker or lighter) version of that color. To me it makes more sense. And you could actually have *two* annotations -- one channel-specific, and one non-channel-specific -- covering the same (or very similar) spans of time and this will look the same / be difficult to differentiate from the what you have here

**Comment by hoechenberger** [comment]
> I expected the channel-specific annotation to only cover the annotated channel(s) rather than spanning all channels in one color and the annotated channel in a different (darker or lighter) version of that color.


I agree

**Comment by mscheltienne** [comment]
> there is I think some sense in having channel-specific annotations be indicated somehow on the non-annotated channels (e.g. so you can see where they are in time when the already-annotated channels are offscreen)

Agree. I like the idea of using the background to denote the difference between a channel-specific and a normal annotation.

**Comment by nmarkowitz** [comment]
Here are some additional mockups.

This one only denotes channel-specific annotation with dashed borders. For channel that span more than the window you wouldn't know an annotation were there (without looking at the bar below). If only one of the borders of the annotation region are shown you wouldn't know in which direction the annotation spans.

<img width="1649" alt="second_mockup" src="https://github.com/mne-tools/mne-qt-browser/assets/34498671/5834cdd0-3dea-4ad1-a509-2b64f8c143ef">

---

Same as before but adds diagonal hatching to annotation region background. Looking at this I'm not a fan of it because the hatching can cause confusion/misreading when looking at the raw traces.

<img width="1649" alt="second_mockup_w_hatching" src="https://github.com/mne-tools/mne-qt-browser/assets/34498671/39276e54-ddef-480c-9e68-34e4b1644f47">

---
Annotation region background has a very low alpha value. In the case where an annotation region spans the entire window, maybe you can tell if it's channel specific by dash borders surrounding the window but that could be confused for boundary of the annotation. 

<img width="1649" alt="second_mockup_w_shading" src="https://github.com/mne-tools/mne-qt-browser/assets/34498671/046caa57-8e9b-4f04-88a1-fc9be28ff3c3">


---

Any other thoughts? I think adding something additional/different to the background of channel-specific annotations would be nice/necessary but I'm trying to think what. Any additional lines/points may confuse the eye when looking at the traces

**Comment by mscheltienne** [comment]
I would definitely keep some background, either with a different alpha and/or with a pattern/dashing added.
The different alpha sounds like a good start, we could always change the background later on.

**Comment by drammock** [comment]
I think the pale alpha is a good compromise here. as @mscheltienne says we can change to a different (i.e. patterned) background later if needed.

In your mockups you have the dashed lines across the top and bottom of the window too, but I think it should be left/right edges only (this shouldn't be too hard since we already have hover effects on left/right edges, so the lines already exist, should be able to just change their styles)

**Comment by nmarkowitz** [comment]
@drammock think I should start trying to write a piece of code to start this? And I agree about the dashed lines only being on the left and right. I was just lazy in my mockup.
