### ISSUE TITLE
Scrolling (and general) performance with large number of annotations

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-qt-browser#161]
With the current version of the browser, a large number of annotations make the browser very sluggish, or even temporarily freezes it. A couple of times today, I had the lovely pop-up: Force to Quit or Wait?

A couple of applications with large number of annotations that I encountered in the past months: 
- sleep recording, 7/8 hours with annotations every 30s to denote e.g. the sleep stage
- 20' recording, 64 channels EEG, with a video game based task where the button press (mouse and keyboard) are logged and saved as annotations

As you can imagine, especially with the second one, the number of annotations sky rocks: 2 876 segments in 20'.

At the moment, I have no idea how the annotations are handled by the browser and what is causing the bottleneck, but it would be good to discuss improvements and optimization of the annotation rendering. After all, the browser does not display that many annotation at once in the view area.

**Comment by cbrnr** [comment]
What is the performance of the Matplotlib-based browser in these cases?

**Comment by larsoner** [comment]
... if you've never line profiled and want to try, this is what I suggested in another thread:

https://github.com/mne-tools/mne-bids-pipeline/issues/609#issuecomment-1481272496

it's fun :)

**Comment by mscheltienne** [comment]
> the bottleneck should be the number shown not the number present overall

Exactly.

I'm short on time at the moment, but yes I will profile both backends, probably next week, with priority given to the Qt backend. Except if someone wants to take a stab at it in the meantime ;)

**Comment by marsipu** [comment]
In early development, I benchmarked multiple ways of updating the shown annotations in Qt for best scroll performance:
1. Only add AnnotRegion (which is a child of pyqtgraph's [LinearRegionItem](https://pyqtgraph.readthedocs.io/en/latest/_modules/pyqtgraph/graphicsItems/LinearRegionItem.html), which handles drawing with [QPainter.drawRect](https://doc.qt.io/qt-6/qpainter.html#drawRect)) to the [PlotItem](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/plotitem.html) (which manages adding [QGraphicsItems](https://doc.qt.io/qt-6/qgraphicsitem.html#QGraphicsItem) to the [QGraphicsScene](https://doc.qt.io/qt-6/qgraphicsscene.html)) when in shown time range.
2. Always add all AnnotRegions for all annotations from the file to PlotItem.

`1.` had the advantage of being more scalable, but `2.` was faster for common amounts of annotations so we discussed the most common usecase and went for `2.` as the current solution. With large amounts of AnnotRegions added to the PlotItem, even the Qt probably struggles under the hood with that many items to be drawn or not drawn in the current viewing window.

As part of a solution we could reimplement solution `1.` above a yet to be determined limit of no. annotations.

But this would still not speed up the second usecase you describe, when you want to improve speed for drawing a lot of annotations on the screen. Maybe creating our own implementation of a Rectangle-Class with calling directly [QPainter.drawRect](https://doc.qt.io/qt-6/qpainter.html#drawRect) might reduce a bit of overhead from pyqtgraph. But I doubt it would speed up drawing much, since the guys from pyqtgraph usually already did a good job in optimizing performance. I think the bottleneck is the qt-backend there. Considering an alternative backend like [vispy](https://github.com/vispy/vispy) might be an option for the future. But that would require a new backend adaption, since the code here relies heavily on pyqtgraph and the Qt-API.

**Comment by larsoner** [comment]
I think it depends on how much faster (2) was. If we're talking (1) as being < 100 us faster than (2) for common use cases, it doesn't matter and we should use (2) all the time.

But a less invasive change is probable to continue with (2) but `setVisible(False)` all annotations. First we should make sure this alleviates the bottleneck (it should, but we should check). Then we use NumPy vectorized math to figure out which annotations are in a specific window/view (fast) and `setVisible(False)` the set of annotations that were shown in the previous view, and `.setVisible(True)` the annotations visible in the new view. I don't think this will add much complexity -- I'll give it a try hopefully this week.

**Comment by larsoner** [comment]
Okay on macOS with:
```
$ root# HOME=/Users/larsoner MNE_DATASETS_SAMPLE_PATH="/Users/larsoner/mne_data" py-spy top -s -r 1000 -- python -u /Users/larsoner/Desktop/rep.py 10000
Collecting samples from 'python -u /Users/larsoner/Desktop/rep.py 10000' and subprocesses
Total Samples 41950
GIL: 72.90%, Active: 100.00%, Threads: 1, Processes 1

  %Own   %Total  OwnTime  TotalTime  Function (filename)                                                                                                        
  0.00%   0.00%   0.000s    40.99s   <module> (rep.py)
  0.00%   0.00%   0.000s    37.03s   plot_raw (<decorator-gen-199>)
  0.00%   0.00%   0.000s    37.03s   plot_raw (mne/viz/raw.py)
  0.00%   0.00%   0.000s    37.03s   plot (mne/io/base.py)
  0.00%   0.00%   0.000s    37.02s   _get_browser (mne/viz/_figure.py)
  0.00%   0.00%   0.000s    33.31s   _init_browser (mne_qt_browser/_pg_figure.py)
  0.00%   0.00%   0.001s    33.12s   func (mne_qt_browser/_pg_figure.py)
  0.00%   0.00%   0.273s    33.12s   __init__ (mne_qt_browser/_pg_figure.py)
  0.00%   0.00%   0.026s    25.34s   _init_annot_mode (mne_qt_browser/_pg_figure.py)
  0.00%   0.00%   0.305s    20.03s   _add_region (mne_qt_browser/_pg_figure.py)
  0.00%   0.00%   0.009s    10.35s   __iter__ (mne/annotations.py)
  0.00%   0.00%   0.086s    10.34s   __getitem__ (mne/annotations.py)
  0.00%   0.00%    2.81s    10.23s   _any_ch_names (mne/annotations.py)
  0.00%   0.00%    3.33s     8.91s   addItem (pyqtgraph/graphicsItems/PlotItem/PlotItem.py)
  0.00%   0.00%    7.42s     7.42s   <genexpr> (mne/annotations.py)
  0.00%   0.00%   0.252s     7.23s   update_annotations (mne_qt_browser/_pg_figure.py)
  0.00%   0.00%   0.316s     6.84s   _get_color (mne_qt_browser/_pg_figure.py)
  0.00%   0.00%   0.113s     5.94s   update_color (mne_qt_browser/_pg_figure.py)
  0.00%   0.00%   0.073s     5.58s   addItem (pyqtgraph/graphicsItems/ViewBox/ViewBox.py)
  0.00%   0.00%    1.18s     5.56s   itemChange (pyqtgraph/graphicsItems/GraphicsObject.py)
...
```
We have some good candidates for speedups. I'll see what I can do...

**Comment by larsoner** [comment]
... and based on the `addItem` being a bottleneck, I think adding all then hiding the not-shown won't fix the problem. I think we need to dynamically add and remove. It looks like this is already done in the AnnotationBar actually, so hopefully we can re-use some code somehow.

**Comment by mscheltienne** [comment]
I had a very quick look through the codebase today, and one potential bottleneck is the (numerous) for loops on the entire set of `AnnotRegion` in `self.mne.regions`. e.g. this one which seems to toggle them visible/not visible:

https://github.com/mne-tools/mne-qt-browser/blob/72fb3699d134890d8d6e6a11b46340f7d2ad0959/mne_qt_browser/_pg_figure.py#L4105-L4109

Instead, looping on the `regions` in the current view would be faster, but we need to keep track of the onset/offset of each region to be able to use some `numpy` math to select the annotations in the current view.
